plugins { id 'com.android.application' }
android {
 namespace 'am.hishatak.field'
 compileSdk 35
 defaultConfig {
   applicationId 'am.hishatak.field'
   minSdk 26
   targetSdk 35
   versionCode 15
   versionName '0.2.4'
 }
 signingConfigs {
   release {
     if (System.getenv('HISHATAK_KEYSTORE_PATH')) {
       storeFile file(System.getenv('HISHATAK_KEYSTORE_PATH'))
       storePassword System.getenv('HISHATAK_STORE_PASSWORD')
       keyAlias System.getenv('HISHATAK_KEY_ALIAS')
       keyPassword System.getenv('HISHATAK_KEY_PASSWORD')
     }
   }
 }
 buildTypes {
   release {
     signingConfig signingConfigs.release
     minifyEnabled false
   }
 }
}
dependencies { implementation 'androidx.core:core:1.15.0' }
